MOD_ID=${mod_id}
MOD_VERSION=${mod_version}
GITHUB_API_BASE_URL=https://api.github.com
LATEST_RELEASE_PATH=/repos/skyblock-wiki/wikitools/releases/latest
LATEST_RELEASE_DOWNLOAD_URL=https://github.com/skyblock-wiki/wikitools/releases/latest
