modId=wikitools
modVersion=${mod_version}
githubApiBaseUrl=https://api.github.com
latestReleasePath=/repos/skyblock-wiki/wikitools/releases/latest
latestReleaseDownloadUrl=https://github.com/skyblock-wiki/wikitools/releases/latest
